### ISSUE TITLE
✨ Add personal fishing sites

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#46]
## Expected Behavior

A user should be able to create and store his own fishing spots with name and gps coordinates.

## Priority

Would be nice to do this sprint.

## Size

1-2

**Comment by balazsorban44** [comment]
@Mortefal 
Perfect place to open the dialog from:

https://github.com/ecatch-kyst/web/blob/df16551905b99e171d5360a5189abeba64bc7a06/src/components/Forms/components/Dropdown.jsx#L65-L75

This component is rendered in the `Dropdown` component, if no result was found. You can define an `onClick` method on this, that sends the user to a desired dialog.

Example:

![image](https://user-images.githubusercontent.com/18369201/53226914-f40f5180-367c-11e9-8774-d2a61cfd5b16.png)

So instead of saying "No option", you could say, "Add your own location", and use the `onClick` prop to render a dialog with some input fields

**Comment by Mortefal** [comment]
Goes into issue #52 , however the issue is almost ready, so remains open
