### ISSUE TITLE
✨ Create push warnings

### ISSUE THREAD

**Issue by Mortefal** [ecatch-kyst/web#82]
Whenever the fisher needs to do something, or should have done something, there should be a push warning to the device that tells the user to do so.
## Expected Behavior

An usecase for this may be when the fisher has sent a DEP message and not sent any DCAs before midnight, as required by law. We can then send a push notification to the mobile device telling the fisher to do this.

## Priority

Not very important, but should be done

## Size

1

**Comment by toretefre** [comment]
My understanding is that push notifications in our project are most needed when the application is not in use, and often when the device is offline, e.g. at sea. 

According to [this site](https://whatwebcando.today/local-notifications.html) this leads us to using the service worker for generating "persistent" notifications which currently is not supported by Safari for iOS according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification#Browser_compatibility), so a good portion of possible users will not benefit from this functionality. 

Do you have any percentage estimate for how many of the fishermen you spoke with, that were using iOS devices @Mortefal?

**Comment by Mortefal** [comment]
I think we just have to do it for the avaliable devices, and not think too much about those not yet supported.

**Comment by balazsorban44** [comment]
Agree with @Mortefal. If we do nothing, we still leave out many users, and the one thing that will change anyway is that Safari for iOS may get support in the future.

**Comment by toretefre** [comment]
The team has decided to abandon this feature due to technical limitations with PWAs. There was a proposal for a Task Scheduler API, but this has not yet been implemented. That means that current technology that are easy to use are not able to schedule what we call "Persistent notification", e.g. notifications that appear even when the PWA is not in use.

[Github thread about Task Scheduler API](https://github.com/whatwg/notifications/issues/69)

This issue will be solved by using a cloud function to send automatic DCAs a few minutes before midnight for the fishers that has last message type DEP. This will also be easier for the fishers to use, as it happens automatically.
